### ISSUE TITLE
Wither boss takes freezing damage.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#10]
Currently, the Wither fight can be cheesed by letting it take damage in the overworld to the freezing damage, I think it'd make more sense if the Wither was immune to taking damage from the freezing given it's a boss mob.

This has become an issue in my modpack as I'm not able to give Wither's frost resistance as apparently that is an effect they are immune to for some strange reason.

**Comment by Jaggwagg** [comment]
This is because the Wither is immune to most status effects. I will add it and the ender dragon to freeze damage immunity.

Edit: In fact, I will probably add an option in the config file that gives users the ability to add whatever mobs they want freeze damage immunity.

**Comment by FrozenDragon0** [comment]
> This is because the Wither is immune to most status effects. I will add it and the ender dragon to freeze damage immunity.
> 
> Edit: In fact, I will probably add an option in the config file that gives users the ability to add whatever mobs they want freeze damage immunity.

That may be a good idea, as there may be some boss mobs from other mods that are also immune to effects.

**Comment by Jaggwagg** [comment]
Added support for custom freezing immune mobs in config.
