### ISSUE TITLE
[Bug]: placeSnow option in the mods config file does not seem to work when set to false.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#13]
**Is this a new bug**
Yes.

**Describe the bug**
When the placeSnow config setting in the mod's config options is set to false it appears it doesn't work at all and still proceeds to freeze over any newly generated chunks.

**To reproduce**
1. Open up the mod's config options.
2. Set the placeSnow config to false at any phase past day 3.
3. Load up a new world and set the day to 3 or above.
4. Observe and notice that any newly generated chunks are still being automatically frozen over.

**Expected behavior**
I expect new chunks to not be frozen over automatically when this config option is false.

**Screenshots**
![2024-01-22_09 21 08](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/346ede80-21cc-4d61-9b39-5674bacf7d80)

Option set for day 9.
![image](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/0132b2ed-2e82-44c4-8439-40d7678fc3ca)

**Additional context**
Trying to turn this off so that way Twilight Forest doesn't freeze over.

**Comment by Jaggwagg** [comment]
Alright, I thoroughly tested it and the dimensions should be checked. I tested it with twilight forest and dimensional doors. Should be fixed (crosses fingers).
