### ISSUE TITLE
[Feature]: Thermal Horse armor.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#14]
**Is this a new feature**
Yes.

**Is your feature request related to a problem? Please describe.**
N.A

**Describe the solution you'd like**
I would like to suggest a thermal armor variant that's designed for horse armor, horses wearing this armor would be immune to freezing and would allow for horses to be more versatile once the apocalypse has taken full affect as at the moment, horses are restricted to requiring light sources everywhere they go to avoid freezing.

**Describe alternatives you've considered**
Alternatively, leather horse armor could be modified to act as a thermal armor source for horses instead of adding new horse armor items.

**Additional context**
I just think this would be a nice feature to have regarding Horses, but of course it doesn't have to be accepted as the mod is meant to be harsh on the surface after all.

**Comment by Jaggwagg** [comment]
Interesting feature. I will add it!

**Comment by Jaggwagg** [comment]
Completed.
