### ISSUE TITLE
[Feature]: Pillagers don't spawn at all at Outposts above the freezing layer.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#19]
**Is this a new bug**
Yes

**Describe the bug**
Essentially, Pillagers at Pillager outposts do not spawn above the freezing layer at all, for the mod on it's own this is fine but when it comes to modpacks this does make raids rather hard to actually trigger.

**To reproduce**
1. Create a new world and set the phase so the freezing layer is in full effect.
2. Head towards a Pillager Outpost and observe that no Pillagers spawn at all.

**Expected behavior**
So for this one I think it's best that a config option be added instead for modpack authors that would allow Pillagers to spawn in outposts above the freezing layer if the option is checked.

**Screenshots**
N.A

**Additional context**
N.A

**Comment by Jaggwagg** [comment]
Changing this to an enhancement for mod config.

**Comment by Jaggwagg** [comment]
Option added. The config option is reference is `allowedSpawningEntities`.
