### ISSUE TITLE
 Any 1.19.2 plan?

### ISSUE THREAD

**Issue by Kasualix** [Jaggwagg/frozen-apocalypse#2]
I want to make a hardcore survival modpack that combines frozen apocalypse and solar apocalyse, but i found there are no kubejs or crt on fabric 1.19.3.
desparate qwq

**Comment by Jaggwagg** [comment]
Right now I am working on a Forge port, so probably not until that's done.

**Comment by Jaggwagg** [comment]
Not doing. If there are more requests I might reopen this issue.
