### ISSUE TITLE
[Bug]: Flowing Water/Lava get snow blocks generated on top of them during snow fall.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#21]
**Is this a new bug**
Yes.

**Describe the bug**
Self-explanatory, but essentially flowing water and lava get snow blocks placed on top of them during snow fall.

**To reproduce**
1. Create a new world and set the apocalypse level to day/phase 6.
2. Make a flowing water/lava down a mountain or a slope.
3. Toggle weather and observe that snow blocks get placed ontop of said water/lava flow.

**Expected behavior**
Flowing lava I think should either be turned into obsidian or cobblestone whilst flowing water should turn into packed Ice as at the moment it looks incredibly strange to see a full block of snow spawning ontop of lava/water flows.

**Screenshots**
![2024-03-12_13 05 07](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/85c702bb-6c0a-4b16-b0ed-4cdfeb8f0a8b)

![2024-03-12_15 15 20](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/4ad1859d-85b7-4240-91a7-4002d7912a87)

**Additional context**

**Comment by Jaggwagg** [comment]
Seems to me that I switched the block checking to not include flowing liquids.

Also, I have not been able to work too much on the mod because of real life things. I will try to work on all these bugs and get them fixed!

**Comment by FrozenDragon0** [comment]
> Seems to me that I switched the block checking to not include flowing liquids.
> 
> Also, I have not been able to work too much on the mod because of real life things. I will try to work on all these bugs and get them fixed!

That's all good, I understand that :)

**Comment by FrozenDragon0** [comment]
So while this was fixed, flowing liquids don't get replaced by anything now, before the block checking was changed flowing water was turned into ice, and I think lava should just turn into stone.
![2024-06-24_13 38 05](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/a6b785e8-3561-477a-aaa8-a39725783af7)

**Comment by Jaggwagg** [comment]
> So while this was fixed, flowing liquids don't get replaced by anything now, before the block checking was changed flowing water was turned into ice, and I think lava should just turn into stone. ![2024-06-24_13 38 05](https://private-user-images.githubusercontent.com/18079316/342214152-a6b785e8-3561-477a-aaa8-a39725783af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzc0MjcsIm5iZiI6MTcxOTIzNzEyNywicGF0aCI6Ii8xODA3OTMxNi8zNDIyMTQxNTItYTZiNzg1ZTgtMzU2MS00NzdhLWFhYTgtYTM5NzI1NzgzYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEzNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MDk3YzQ3NDU5NmFlYWFhY2JhOTkyNDk5ZmU5ZWQ1NjIyYzAyMDNmYTlmNGNjYTcyODRiZWYxZjE0MDNhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0LzOxP9HROWDhUlGspKpCgYNcMa4KncCPRgw2LW9k8)

This is expected behavior as only source fluids would be able to turn into a block counterpart to prevent extra block duplication. For example, a lava source block can turn into obsidian, but not the flowing liquid, same with water!
