### ISSUE TITLE
[Bug]: Entities in boats still freeze to death when near light source blocks.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#24]
**Is this a new bug**
Yes.

**Describe the bug**
Self-explanatory but essentially when an entity is in a boat the mod will still proceed to freeze them despite the fact they are next to a light source block.

**To reproduce**
1. Place down a boat and get any entity inside it and surround the boat with light source blocks.
2. Set the apocalypse phase so the freezing layer is low enough.
3. Observe and notice the entity inside the boat is taking freezing damage despite being right next to light source blocks.

**Expected behavior**
I expect entities inside boats to not take freezing damage when next to light source blocks.

**Screenshots**
Villager here in a boat taking freezing damage despite being right next to glowstone blocks.
![2024-04-22_16 34 45](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/7091c797-90ac-442f-b0e1-8ebf29210e48)

**Additional context**
N.A

**Comment by FrozenDragon0** [comment]
Note: This is the case on both Fabric and Forge, noticed on Forge first and tested it on Fabric.

**Comment by Jaggwagg** [comment]
Minecraft is too glitchy. For some reason, the block light can be 0 at random intervals if an entity is riding something. Even players viewing the F3 menu can see this, block light is 0 even though it is not.

**Comment by Jaggwagg** [comment]
Fixed it! Minecraft defaults an entity block position to the feet, and if they are riding something, their feet is in the ground! Also made a fix for if a player or entity is inside a one block high area.
