### ISSUE TITLE
[Bug]: Strong light source blocks such as glowstone or lava should prevent icicles from forming.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#27]
**Is this a new feature**
Yes.

**Describe the solution you'd like**
Essentially, strong light sources blocks like glowstone or lava would melt icicles/prevent them from forming near them.
Currently the icicles are a unique block given how cold it'd be for them to form, however they also present an issue of being a rather annoying block if close to the surface, and it does look a little strange when icicles form on light emitting blocks.

**Comment by Jaggwagg** [comment]
Great suggestion, will add this in the next update.
