### ISSUE TITLE
[Bug]: Icicles do not have an assigned tool set for them causing them take a few seconds to break.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#30]
**Is this a new bug**
Yes.

**Describe the bug**
Self-explanatory really, but essentially icicles cannot be broken in a fast manner with a pickaxe or any tool as they don't have an assigned tool level set for them, fastest way to remove icicles is to remove the block that they are placed on and let them fall down.

**Expected behavior**
I expect icicles to be broken in a fast manner if a pickaxe is used on them.

**Additional context**
Icicles also have no way to be obtained in survival unless they fall to the ground when their support block is broken, this really doesn't make much sense as the icicle would shatter upon hitting the floor when falling like this, so I propose that icicles function the same as ice blocks in terms of their drops and have it so they can only be acquired via silk touch.

**Comment by Jaggwagg** [comment]
Fixed!
