### ISSUE TITLE
[Feature]: Add a config option to allow packed ice to turn into blue ice.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#31]
**Is this a new feature**
Yes.

**Describe the solution you'd like**
As the title suggests, a simple config option in the mod to allow packed ice to be turned into blue ice if exposed.

**Additional context**
If this config option is enabled this would also make it so any new chunks generated with water on the surface be blue ice instead of packed ice.

**Comment by Jaggwagg** [comment]
Please make this a seperate issue: `If this config option is enabled this would also make it so any new chunks generated with water on the surface be blue ice instead of packed ice.`

Otherwise. Done!
