### ISSUE TITLE
[Bug]: Frozen Apocalypse unable to pass through semi-solid blocks.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#32]
**Is this a new bug**
Yes.

**Describe the bug**
Essentially, blocks such as signs/fences/iron bars/glass panes are able to be used to shield specific blocks from the apocalypse which looks incredibly silly given the nature of these blocks.

**Expected behavior**
I expect Frozen Apocalypse to not be blocked by semi-solid blocks.

**Screenshots**
Here you can see these various blocks are able to prevent the grass block below them from turning into permafrost despite the apocalypse being in full effect.
![2024-06-23_15 09 34](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/6b236a0e-b0e2-4a54-b185-caaa3b76571f)

**Additional context**
All blocks I've found so far:
![2024-06-23_15 24 09](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/8da74833-edc2-47f7-a425-b53beba6c8f2)

**Comment by Jaggwagg** [comment]
This is an expected behavior as snow or rain doesn't pass through any block type in vanilla.
