### ISSUE TITLE
[Suggestion] Config option to change what day each phase occurs on.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#4]
Essentially, this would just be config options to allow you to change what days each phase occurs on, and I think this would benefit those who want some extended time to prepare before the full apocalypse kicks in, this would be similar to SmushyTaco's Solar Apocalypse mod which allows the days that each phase occurs on to be changed.

**Comment by Jaggwagg** [comment]
This seems like a good feature, I will work on it for 1.1.2.

**Comment by FrozenDragon0** [comment]
> This seems like a good feature, I will work on it for 1.1.2.

Awesome! I've been thinking of potentially using this mod in my Forge modpack to replace Solar Apocalypse with, hence why I suggested this :D 

If I think of anymore suggestions of this mod I'll be sure to open issues with said suggestions!

**Comment by Jaggwagg** [comment]
Implemented, closing issue
