### ISSUE TITLE
[Suggestion] Config option to change the distance entities need to be from a light source to avoid freezing.

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#5]
Basically this would be a config option that would allow you to change how far you need to be from a light source to avoid freezing to death, each light source would be able to have it's config from 0 to 15.

Ex: Lava sources would be able to have the highest level, whereas weaker light sources such as torches would have a lower level, would be changeable in the config.

This would also support light source blocks added by other mods.

**Comment by Jaggwagg** [comment]
Should be relatively easy, will consider this for the 1.1.2 release

**Comment by Jaggwagg** [comment]
Implemented, but this might have some performance issues. I tried optimizing it the best I could, and I can handle around 100-200 entities around a light source before I notice a drop in performance. A normal play through should be fine.

I will reopen this issue if there are problems.
