### ISSUE TITLE
Disable unwanted mob spawning above Y level freezing point

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#6]
Currently, I've noticed that mobs that die from the Apocalypse still drop their items which can lead to performance problems and server lag, this is most prominent with Ocean biomes and the amount of squids/fish dying from the Apocalypse resulting in a lot of item build up under the frozen oceans.

All these items are merely just from mobs dying from the Apocalypse and dropping their items in the process.
![2023-12-08_09 43 13](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/d92ad971-0f7f-4805-beb3-bcb2d37d4691)

**Comment by Jaggwagg** [comment]
Renamed title from "[Suggestion] Disable mobs from dropping items if they are killed from the Apocalypse directly." to "Disable unwanted mob spawning above Y level freezing point"

**Comment by FrozenDragon0** [comment]
Should probably also mention that this would only affect natural mob spawns, things such as Monster Spawners, Raids or structure specific mob spawning such as Pillagers in their outposts or Guardians from Ocean monuments will still continue to spawn as normal.

**Comment by Jaggwagg** [comment]
Implemented, closing issue
