### ISSUE TITLE
Add weather options in the config

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#7]
Currently weather is disabled after day 6 which is understandable given the sun being further away from the Earth, however there's two problems with this.

1 Being the Riptide enchantment's usefulness, given no rain and oceans/rivers being frozen over this makes Elytra's almost impossible to use in the Overworld, especially for cases in which rocket boosting is disabled which is the case in my pack and Riptide serving as a replacement.

2. Mob heads impossible to acquire if thunder doesn't occur, which in turn also makes the channeling enchantment useless for Tridents.

**Comment by Jaggwagg** [comment]
I will say though, this is suppose to be an apocalypse, making the surface very harsh (just to keep in mind for future suggestions, config options are fine)

**Comment by Jaggwagg** [comment]
Implemented, closing issue
