### ISSUE TITLE
Issue with heat source blocks not being properly added in the config during startup (race condition)

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#8]
Self-explanatory, but whenever I tried adding Glowstone blocks to the config file for heat source blocks it didn't register and I was still freezing despite standing right next to the Glowstone.

Though I've also noticed that the config doesn't seem to accept any other light emitting blocks at all, even modded ones, as to whether this is a bug with Forgified Fabric API/Connector or an actual bug with the mod I'm not sure.

**Comment by Jaggwagg** [comment]
Okay, I tested it and it looks like mods that register after my mod will not work. So I will need to defer the block checking until then.
Adding normal Minecraft blocks worked for me, so send me you're Minecraft log file if possible (it probably has something to do with Forgified Fabric).

Another note, glowstone and other blocks should give heat, so I will add those to the default heat blocks.

**Comment by FrozenDragon0** [comment]
[latest.log](https://github.com/Jaggwagg/frozen-apocalypse-mod/files/13709209/latest.log)

**Comment by Jaggwagg** [comment]
@FrozenDragon0 Yeah, I'm not seeing the config file being loaded at all in the logs. Can you verify that the other config options work?

**Comment by FrozenDragon0** [comment]
> @FrozenDragon0 Yeah, I'm not seeing the config file being loaded at all in the logs. Can you verify that the other config options work?

Odd, and this is all the config file gives me. I don't get any other options from it strangely whereas on Fabric I do.
![image](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/dce4d832-0b3a-4b04-9ec5-c9b41e41e584)

**Comment by Jaggwagg** [comment]
Go ahead and delete your current config file as the config files before 1.1 release are broken, this should generate a new config. You can copy the block values over before you delete it of course.

All config files from now on have a version number attached so this shouldn't be a problem anymore. I'm still curious if the modded blocks using Forgified Fabric will work.

**Comment by FrozenDragon0** [comment]
Well the new config works, I'm able to add other light sources now, though unfortunately it seems modded blocks aren't registered.
![image](https://github.com/Jaggwagg/frozen-apocalypse-mod/assets/18079316/18162a17-018b-426f-bbb6-e0ca2c0f3caa)

**Comment by Jaggwagg** [comment]
Fixed the issue. Tested with Sinytra Connector in Forge as well as pure Fabric.
