### ISSUE TITLE
Crash with Forgified Fabric because of version issues

### ISSUE THREAD

**Issue by FrozenDragon0** [Jaggwagg/frozen-apocalypse#9]
It seems since 1.1.2 the mod no longer likes Forgified Fabric apparently and immediately crashes upon trying to join a world unless you're in spectator mode. Tested on pure Fabric also and it works fine there.

While I'm not familiar with reading crash reports it appears that the crash is related to ticking.
[crash-2023-12-23_12.23.20-server.txt](https://github.com/Jaggwagg/frozen-apocalypse-mod/files/13757997/crash-2023-12-23_12.23.20-server.txt)

**Comment by Jaggwagg** [comment]
Refer to this issue: https://github.com/Sinytra/Connector/issues/432.

It seems that my mod works for everything except networking in 1.20.1, but my mod is for 1.20.2. I use networking to sync the apocalypse level across the server and client for sun size.

I was planning on adding an option that disables sun size changes (and also allows size customizability), which should fix the issue (unfortunately with no sun size changes using Forgified Fabric).

**Comment by Jaggwagg** [comment]
"Fixed", although with the cost of sun size changing must be disabled using Forgified Fabric for now.

Forgified Fabric users must set `SUN_SIZE_CHANGES_ENABLED` to `false` in the config file.

**Comment by FrozenDragon0** [comment]
> Refer to this issue: [Sinytra/Connector#432](https://github.com/Sinytra/Connector/issues/432).
> 
> It seems that my mod works for everything except networking in 1.20.1, but my mod is for 1.20.2. I use networking to sync the apocalypse level across the server and client for sun size.
> 
> I was planning on adding an option that disables sun size changes (and also allows size customizability), which should fix the issue (unfortunately with no sun size changes using Forgified Fabric).

That's all good, as long as the rest of the mod works for Forgified Fabric then that's a sacrifice I'm willing to make, and I agree that it is indeed very strange that the mod even works on 1.20.1 to begin with for Forgified Fabric as I tried it for pure Fabric on 1.20.1 and the game immediately crashed.

I'm just unfortunately stuck with 1.20.1 until Forgified Fabric eventually moves to Neoforge and updates to 1.20.2 and beyond which I have no idea when that's going to happen.

**Comment by Jaggwagg** [comment]
This is older news, but I was accidentally transferring the wrong type of value to each player. It should be fixed and sun size should work on Forgified Fabric, especially since I downgraded to 1.20.1.

**Comment by FrozenDragon0** [comment]
> This is older news, but I was accidentally transferring the wrong type of value to each player. It should be fixed and sun size should work on Forgified Fabric, especially since I downgraded to 1.20.1.

Ah, sweet, does the newest update contain a dimension config btw? I was looking through the source code and noticed AffectedDimension.java which got me curious as to whether the next update will allow you to specify which dimensions the mod affects.

**Comment by Jaggwagg** [comment]
> > This is older news, but I was accidentally transferring the wrong type of value to each player. It should be fixed and sun size should work on Forgified Fabric, especially since I downgraded to 1.20.1.
> 
> Ah, sweet, does the newest update contain a dimension config btw? I was looking through the source code and noticed AffectedDimension.java which got me curious as to whether the next update will allow you to specify which dimensions the mod affects.

Yes, that's exactly what it's for! Part of the next update.

**Comment by FrozenDragon0** [comment]
> > > This is older news, but I was accidentally transferring the wrong type of value to each player. It should be fixed and sun size should work on Forgified Fabric, especially since I downgraded to 1.20.1.
> > 
> > 
> > Ah, sweet, does the newest update contain a dimension config btw? I was looking through the source code and noticed AffectedDimension.java which got me curious as to whether the next update will allow you to specify which dimensions the mod affects.
> 
> Yes, that's exactly what it's for! Part of the next update.

Awesome! That'll be useful as I only discovered a bug with my pack yesterday with Frozen Apocalypse taking effect in a modded dimension that it's not meant to haha.
